In [1]:
import pandas as pd

df = pd.read_csv('data/drafts.csv') #import drafts file

heroes_df = pd.read_csv('data/basic_heroes.csv') #import heroes file
heroes_df = heroes_df [['id','localized_name']].set_index('id')
heroes_dict=heroes_df.to_dict() #create dictionary of heroes
heroes_dict = heroes_dict['localized_name']

In [2]:
# Count number of times hero was banned
hero_bans = pd.DataFrame(df[df.pick == False]['hero_id'].value_counts()).reset_index()
hero_bans.columns=['hero_id','num_bans']

# Count number of times hero was picked
hero_picks = pd.DataFrame(df[df.pick == True]['hero_id'].value_counts()).reset_index()
hero_picks.columns=['hero_id','num_picks']

SyntaxError: invalid syntax (<ipython-input-18-c4b98359eacd>, line 2)

In [23]:
matches_won=pd.read_csv('data/hero_matches_won.csv')
heroes_dict=heroes_df.to_dict() #create dctionary of heroes
heroes_dict = heroes_dict['localized_name']
matches_won['hero_name']=matches_won['hero_id'].replace(heroes_dict) #replace hero_id with hero names
matches_won.to_csv('output/heroes_matches_won_name.csv')

In [10]:
players = pd.read_csv('data/basic_player.csv')
players[['account_id','match_id','hero_id','player_side']]

      account_id    match_id  hero_id player_side
0       54580962  3966752666      110     radiant
1       86738694  3966752666       80     radiant
2      152962063  3966752666      106     radiant
3       77490514  3966752666      104     radiant
4      401792574  3966752666      107     radiant
5       57516313  3966752666       31        dire
6       26356855  3966752666       85        dire
7      121769650  3966752666       25        dire
8       62533910  3966752666        4        dire
9       92367063  3966752666      120        dire
10      19672354  4061952570       58     radiant
11     311360822  4061952570      114     radiant
12      26771994  4061952570        7     radiant
13      88271237  4061952570       45     radiant
14      94054712  4061952570       19     radiant
15      82262664  4061952570       66        dire
16      34505203  4061952570        4        dire
17     105248644  4061952570       74        dire
18     101356886  4061952570       88        dire
19      72312627  4061952570       70        dire
20     125581247  4080778303       10     radiant
21     106863163  4080778303        4     radiant
22      94296097  4080778303       58     radiant
23     101695162  4080778303      100     radiant
24      94738847  4080778303       78     radiant
25      19672354  4080778303       66        dire
26     311360822  4080778303       12        dire
27      26771994  4080778303       91        dire
28      88271237  4080778303        2        dire
29      94054712  4080778303       74        dire
...          ...         ...      ...         ...
7940    28070572  3891013861       98     radiant
7941   175105750  3891013861       88     radiant
7942    97975407  3891013861       16     radiant
7943    99796146  3891013861       64     radiant
7944   185202677  3891013861       54     radiant
7945   202217968  3891013861       49        dire
7946    91369376  3891013861      109        dire
7947   111291593  3891013861       57        dire
7948   103940975  3891013861       52        dire
7949   103039499  3891013861       30        dire
7950    84772440  3893222060       69     radiant
7951   100471531  3893222060       91     radiant
7952    89871557  3893222060       72     radiant
7953    91443418  3893222060        3     radiant
7954   113457795  3893222060       98     radiant
7955   184950344  3893222060      112        dire
7956   155494381  3893222060      101        dire
7957   164532005  3893222060       49        dire
7958   132309493  3893222060       10        dire
7959   187619311  3893222060        2        dire
7960    28070572  3888646761       43     radiant
7961   155332459  3888646761      100     radiant
7962    97975407  3888646761       65     radiant
7963    99796146  3888646761        3     radiant
7964   185202677  3888646761      114     radiant
7965    87278757  3888646761       64        dire
7966    97590558  3888646761       77        dire
7967    89117038  3888646761        7        dire
7968    86799300  3888646761       69        dire
7969   116585378  3888646761       63        dire

[7970 rows x 4 columns]

In [12]:
matches = pd.read_csv('data/basic_match.csv')
matches[['match_id','radiant_win']]

       match_id  radiant_win
0    3966752666        False
1    4061952570        False
2    4080778303        False
3    3962701540        False
4    3967062172         True
5    3965702859        False
6    3971583578        False
7    3967480317        False
8    4078478649         True
9    4063266100        False
10   4062098446        False
11   3960615221         True
12   3965779077         True
13   3961291740         True
14   4078291886        False
15   4061662358         True
16   3971470160         True
17   4070746269         True
18   3961000985         True
19   4074821374        False
20   3961505531        False
21   4061660411        False
22   3962882047         True
23   4066822873        False
24   3967727113        False
25   4076114893        False
26   3969775882        False
27   4066615144        False
28   4065211218         True
29   3965525689        False
..          ...          ...
767  3899867571        False
768  3902849890        False
769  3893538521         True
770  3891925312        False
771  3898771485         True
772  3899984103         True
773  3902498542        False
774  3900489066         True
775  3888897233        False
776  3891767458         True
777  3891255300        False
778  3900169897         True
779  3889421559        False
780  3888710999        False
781  3899726029        False
782  3890836890         True
783  3890976184         True
784  3893059114         True
785  3891024973         True
786  3898369901         True
787  3891640110        False
788  3893448698        False
789  3889358128         True
790  3891198578         True
791  3891483725        False
792  3891663985         True
793  3888583323        False
794  3891013861        False
795  3893222060         True
796  3888646761        False

[797 rows x 2 columns]

In [3]:
# Merge the ban pick data and add column with hero name
merged=hero_bans.merge(hero_picks,how='outer',on='hero_id')
merged['hero_name']=merged['hero_id'].replace(heroes_dict) #replace hero_id with hero names
merged.fillna(0,inplace=True)
merged['sum_pickban']=merged['num_bans'].add(merged['num_picks'])
merged

     hero_id  num_bans  num_picks            hero_name  sum_pickban
0         91       549       77.0                   Io        626.0
1         12       316      134.0       Phantom Lancer        450.0
2         77       281       96.0                Lycan        377.0
3         66       276       70.0                 Chen        346.0
4         60       276      105.0        Night Stalker        381.0
5         89       258      141.0           Naga Siren        399.0
6         43       196      146.0        Death Prophet        342.0
7         53       179       86.0     Nature's Prophet        265.0
8          4       177       88.0          Bloodseeker        265.0
9         38       170      155.0          Beastmaster        325.0
10        57       167       68.0           Omniknight        235.0
11        61       166       33.0          Broodmother        199.0
12        51       166      133.0            Clockwerk        299.0
13        19       160      128.0                 Tiny        288.0
14        58       155       40.0          Enchantress        195.0
15        49       146      161.0        Dragon Knight        307.0
16         3       145      173.0                 Bane        318.0
17        10       142       82.0            Morphling        224.0
18        92       141       53.0               Visage        194.0
19        16       139      190.0            Sand King        329.0
20        54       139       88.0          Lifestealer        227.0
21        72       131      169.0           Gyrocopter        300.0
22        52       129      179.0              Leshrac        308.0
23         9       126      154.0               Mirana        280.0
24       106       123      112.0         Ember Spirit        235.0
25        23       122       96.0               Kunkka        218.0
26        63       122       71.0               Weaver        193.0
27        93       121       63.0                Slark        184.0
28        62       121       39.0        Bounty Hunter        160.0
29        25       119      148.0                 Lina        267.0
..       ...       ...        ...                  ...          ...
85        22        25       43.0                 Zeus         68.0
86        82        25        8.0                Meepo         33.0
87         7        24       72.0          Earthshaker         96.0
88       113        24       18.0           Arc Warden         42.0
89        98        23       23.0            Timbersaw         46.0
90        39        22       44.0        Queen of Pain         66.0
91       104        19       30.0     Legion Commander         49.0
92         8        19       32.0           Juggernaut         51.0
93        99        17       14.0          Bristleback         31.0
94       111        15       40.0               Oracle         55.0
95        81        14       21.0         Chaos Knight         35.0
96        90        14       20.0  Keeper of the Light         34.0
97        27        13       29.0        Shadow Shaman         42.0
98        14        12        9.0                Pudge         21.0
99        83        11       25.0     Treant Protector         36.0
100       28        11       35.0              Slardar         46.0
101      107        11       49.0         Earth Spirit         60.0
102       26        10       58.0                 Lion         68.0
103       84        10       33.0            Ogre Magi         43.0
104       79        10       46.0         Shadow Demon         56.0
105        1         8       13.0            Anti-Mage         21.0
106      105         8        0.0              Techies          8.0
107       31         8       23.0                 Lich         31.0
108       44         7       18.0     Phantom Assassin         25.0
109       71         7       14.0       Spirit Breaker         21.0
110       96         7       22.0    Centaur Warrunner         29.0
111       18         5       10.0                 Sven         15.0
112       35         2        9.0               Sniper         11.0
113       50         2       15.0               Dazzle         17.0
114       32         2        6.0                 Riki          8.0

[115 rows x 5 columns]

In [5]:
merged.to_csv('output/num_pickbans.csv',index=False)